// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRefreshTokenDetails.sql

package database

import (
	"context"
)

const getRefreshTokenDetails = `-- name: GetRefreshTokenDetails :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at from refresh_tokens where token=$1
`

func (q *Queries) GetRefreshTokenDetails(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenDetails, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
