// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getUserChirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirpsForUser = `-- name: GetChirpsForUser :many
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE user_id = $1
ORDER BY
  CASE WHEN $2 = 'desc' THEN created_at END DESC,
  CASE WHEN $2 <> 'desc' THEN created_at END ASC
`

type GetChirpsForUserParams struct {
	UserID        uuid.UUID
	SortDirection interface{}
}

func (q *Queries) GetChirpsForUser(ctx context.Context, arg GetChirpsForUserParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getChirpsForUser, arg.UserID, arg.SortDirection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
